In [16]:
import numpy as np

In [17]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [18]:
a


array([[1, 2],
       [3, 4]])

In [19]:
b

array([[5, 6]])

In [20]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
np.concatenate((a,b), axis=None)

array([1, 2, 3, 4, 5, 6])

#https://www.kaggle.com/learn

In [22]:
#check round 
print(round(2.3))
print(round(2.5))
print(round(2.6))

print(round(2.3, 0))

print(round(2.6, 1))

print(round(3.5))
print(round(3.6))

print("=check=")
print(round(2.5))
print(round(3.5))

2
2
3
2.0
2.6
4
4
=check=
2
4


In [23]:

print(3 * True)
print(-3.1 * True)
print(3.1 * False)
print(type("abc" * False))
print("abc"*False)
print(len("abc" * False))

3
-3.1
0.0
<class 'str'>

0


In [13]:
import math
math.ceil(3.2)


4

In [14]:
math.ceil(2.5)

3

In [15]:
print(math.ceil(1.4))
print(math.ceil(5.3))
print(math.ceil(-5.3))
print(math.ceil(22.6))
print(math.ceil(10.0))

2
6
-5
23
10


In [27]:
round(11.5)

12

In [26]:
round(12.5)

12

In [28]:
round(13.5)

14

In [29]:
round(22.5)

22

In [30]:
round(422.5)

422

In [31]:
round(22.45,-1)

20.0

In [32]:
round(1352,-2)

1400

In [33]:
math.ceil(3.2)

4

In [34]:
math.floor(3.2)

3

In [24]:

# get_expected_cost(1, 1, False)
# get_expected_cost(2, 1, True)
def get_expected_cost(beds, baths, has_basement):
   
    value = 80000 + beds*30000 + baths*10000 + has_basement*40000
    return value


In [25]:
# project_one = cost_of_project("Charlie+Denver", True)
def cost_of_project(engraving, solid_gold): # BOOL : solid_gold
    cost = solid_gold* (100 +  10 * len(engraving)) + (not solid_gold) * ( 50 + 7 * len(engraving))
    return cost


In [36]:
total_candies =2

if total_candies == 1:
    print("Splitting 1 candy")
else:
    print("Splitting", total_candies, "candies")
#Here's a slightly more succinct solution using a conditional expression:

print("Splitting", total_candies, "candy" if total_candies == 1 else "candies")

Splitting 2 candies
Splitting 2 candies


In [39]:
r = ["Mario", "Bowser", "Luigi"]
r[-1][1]

'u'

In [40]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
for planet in planets:
    print(planet, end=' ') # print all on same line

Mercury Venus Earth Mars Jupiter Saturn Uranus Neptune 

In [41]:

def elementwise_greater_than(L, thresh):
    res = []
    for ele in L:
        res.append(ele > thresh)
    return res

#And here's the list comprehension version:

def elementwise_greater_than(L, thresh):
    return [ele > thresh for ele in L]

In [42]:
planet = "abc"
pluto_mass = 1.303 * 10**22
earth_mass = 5.9722 * 10**24
population = 52910390
#         2 decimal points   3 decimal points, format as percent     separate with commas

"{} weighs about {:.2} kilograms ({:.3%} of Earth's mass). It is home to {:,} Plutonians.".format(
    planet, pluto_mass, pluto_mass / earth_mass, population,
)

"abc weighs about 1.3e+22 kilograms (0.218% of Earth's mass). It is home to 52,910,390 Plutonians."

In [1]:
def word_search(doc_list, keyword):
    """
    Takes a list of documents (each document is a string) and a keyword. 
    Returns list of the index values into the original list for all documents 
    containing the keyword.

    Example:
    doc_list = ["The Learn Python Challenge Casino.", "They bought a car", "Casinoville"]
    >>> word_search(doc_list, 'casino')
    >>> [0]
    """
    indices = []
    for i, doc in enumerate(doc_list):
        tokens = doc.split()
        normalized = [token.rstrip('.,').lower() for token in tokens]
        if keyword.lower() in normalized:
            indices.append(i)
    return indices
    pass 

In [2]:
def multi_word_search(doc, keywords):
    """
    Takes list of documents (each document is a string) and a list of keywords.  
    Returns a dictionary where each key is a keyword, and the value is a list of indices
    (from doc_list) of the documents containing that keyword

    >>> doc_list = ["The Learn Python Challenge Casino.", "They bought a car and a casino", "Casinoville"]
    >>> keywords = ['casino', 'they']
    >>> multi_word_search(doc_list, keywords)
    {'casino': [0, 1], 'they': [1]}
    """
    keyword_to_indices = {}
    for keyword in keywords:
        keyword_to_indices[keyword] = word_search(doc, keyword)
    return keyword_to_indices
    pass
 

In [3]:
doc_list = ["The Learn Python Challenge Casino.", "They bought a car and a casino", "Casinoville"]
keywords = ['casino', 'they']
for i, doc in enumerate(doc_list):
        tokens = doc.split()
        normalized = [token.rstrip('.,').lower() for token in tokens]
        print(normalized)


['the', 'learn', 'python', 'challenge', 'casino']
['they', 'bought', 'a', 'car', 'and', 'a', 'casino']
['casinoville']


In [4]:
multi_word_search(doc_list, keywords)

{'casino': [0, 1], 'they': [1]}

In [5]:
import math

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [ ]:
print(help(math))

In [7]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [8]:
print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [10]:
round(math.pi, 3)

3.142

In [9]:
math.log(32, 2)

5.0

In [11]:
# Import the jimmy_slots submodule
from learntools.python import jimmy_slots

def prettify_graph(graph):
    """Modify the given graph according to Jimmy's requests: add a title, make the y-axis
    start at 0, label the y-axis. (And, if you're feeling ambitious, format the tick marks
    as dollar amounts using the "$" symbol.)
    """
    
    graph.set_title("Results of 500 slot machine pulls")
    # Make the y-axis begin at 0
    graph.set_ylim(bottom=0)
    # Label the y-axis
    graph.set_ylabel("Balance")
    # Bonus: format the numbers on the y-axis as dollar amounts
    # An array of the values displayed on the y-axis (150, 175, 200, etc.)
    ticks = graph.get_yticks()
    # Format those values into strings beginning with dollar sign
    new_labels = ['${}'.format(int(amt)) for amt in ticks]
    # Set the new labels
    graph.set_yticklabels(new_labels)

graph = jimmy_slots.get_graph()
prettify_graph(graph)
graph

ModuleNotFoundError: No module named 'learntools'

In [19]:
import pandas as pd 
fruits = pd.DataFrame([[30, 21]], columns = ["Apples","Bananas"])
print(fruits)


   Apples  Bananas
0      30       21


In [20]:
fruit_sales = pd.DataFrame([[35, 21], [41, 34]], columns=['Apples', 'Bananas'],
                index=['2017 Sales', '2018 Sales'])
print(fruit_sales)

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34


In [21]:
quantities = ['4 cups', '1 cup', '2 large', '1 can']
items=  ['Flour', 'Milk', 'Eggs', 'Spam']
ingredients = pd.Series (quantities, index=items, name='Dinner')
print(ingredients)

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object


In [25]:
reviews.loc[:, ['taster_name', 'taster_twitter_handle', 'points']]
reviews.loc[(reviews.country == 'Italy') & (reviews.points >= 90)]
reviews.loc[reviews.country.isin(['Italy', 'France'])]
reviews.loc[reviews.price.notnull()]

indices = [1, 2, 3, 5, 8]
sample_reviews = reviews.loc[indices]

sample_reviews = reviews.loc[[1,2,3,5,8]]

NameError: name 'reviews' is not defined

In [ ]:
df = reviews.loc[[0,1,10,100], ['country', 'province', 'region_1', 'region_2']]
 
cols = ['country', 'variety']
df = reviews.loc[:99, cols]
or

cols_idx = [0, 11]
df = reviews.iloc[:100, cols_idx]

top_oceania_wines = reviews.loc[(reviews.country.isin(['Australia', 'New Zealand'])) & (reviews.points >= 95)]

In [ ]:
review_points_mean = reviews.points.mean()
reviews.points.map(lambda p: p - review_points_mean)
def remean_points(row):
    row.points = row.points - review_points_mean
    return row

reviews.apply(remean_points, axis='columns')

In [ ]:
n_trop = reviews.description.map ( lambda desc: "tropical" in desc ).sum()
n_fruity = reviews.description.map( lambda desc : "fruity" in desc ).sum()
descriptor_counts =  pd.Series([n_trop, n_fruity], index=['tropical', 'fruity'])

In [ ]:
def stars(row) :
    if row.country == 'Canada':
        return 3
    elif row.points >= 95:
        return 3
    elif row.points >= 85:
        return 2
    else:
        return 1
star_ratings = reviews.apply(stars, axis='columns')

# Check your answer
q7.check()

In [ ]:
reviews_written = reviews.groupby('taster_twitter_handle').taster_twitter_handle.count()
reviews_written = reviews.groupby('taster_twitter_handle').size()
reviews_written = reviews.taster_twitter_handle.value_counts()

In [26]:
reviews.rename(columns={'points': 'score'})
renamed = reviews.rename(columns = dict(region_1='region', region_2 = 'locale'))


NameError: name 'reviews' is not defined

In [ ]:
reviews.rename(index={0: 'firstEntry', 1: 'secondEntry'})
reviews.rename_axis("wines", axis='rows').rename_axis("fields", axis='columns')